language: csharp
solution: tools.sln
mono: none
dist: trusty

script:
    - cd ~
    - wget https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-ubuntu-x64.deb
    - sudo dpkg -i dotnet-sdk-latest-ubuntu-x64.deb
    - dotnet restore
    - dotnet test