version: '1.0.{build}'
configuration:
  - Release

image: Visual Studio 2017 RC
 
install: 
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build: 
  - cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%
  - cmd: nuget install nuget.commandline -source https://dotnet.myget.org/F/nuget-build -prerelease -excludeversion
  - cmd: set PATH=%appveyor_build_folder%\NuGet.CommandLine\tools;%PATH%
  - cmd: nuget restore RefactoringEssentials.2017\RefactoringEssentials.csproj
  - cmd: nuget restore RefactoringEssentials.2017.sln

build:
  project: TheLizzards.sln

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'
